### ISSUE TITLE
Add rōmaji to Signs page

### ISSUE THREAD

**Issue by motss** [Lorti/phrasebook#5]
Signs page has no hiragana annotations.

**Comment by Lorti** [comment]
What do you mean by annotations? Do you mean `<ruby>` elements for furigana?

<ruby>
  明日 <rp>(</rp><rt>Ashita</rt><rp>)</rp>
</ruby>

**Comment by motss** [comment]
You're right. I mean missing furigana.

Attached the screenshot below.

![Screenshot_20190312-230651](https://user-images.githubusercontent.com/10607759/54211210-e2062d80-451b-11e9-8c48-3c8f67bd157b.jpg)

**Comment by Lorti** [comment]
No page has furigana, as of now. Not just the signs page. I will rename your issue.

**Comment by Lorti** [comment]
I have already added hiragana data to some phrases, but only the ones that the speech synthesis wouldn’t read correctly. 

So to get furigana one has to 
1. think about how and when to display furigana
2. and add missing hiragana data to all phrases.

The first task raises a few other questions, such as:
  * Does every phrase need to display furigana? I’d say only the ones with Kanji, but how do you distinguish between them?
  * Shall we add a toggle to the settings? 
  * How can the furigana stay readable on all screens? Right now they'd be extremely small.
  * Is a toggle for displaying hiragana instead or below the Japanese phrases a better solution?

I’d be happy if someone wants to chime in and open a pull request, at the moment I’m too busy with other projects 🙂

**Comment by motss** [comment]
> No page has furigana, as of now. Not just the signs page. I will rename your issue.

If that's the case then it isn't the _furigana_ I'm talking about. For instance, the `Basic` page has all the annotations or whatever it is called one needs to know how to pronounce each kanji and hiragana.

![Screenshot_20190313-181349](https://user-images.githubusercontent.com/10607759/54285561-2c9bae80-45dd-11e9-916c-48be82b9ebc7.jpg)

**Comment by Lorti** [comment]
Ah, sorry. Then you mean rōmaji. Yes, I can definitely add those ;)

**Comment by motss** [comment]
rōmaji, that's the word!

**Comment by Lorti** [comment]
I didn't add romaji to push and pull, as those are just parts of a word. This would also be the case for small, middle and large, but I just added the adjectives as pronunciation. Although they would require more characters than just the Kanji.
It should be deployed on the page in a minute.

**Comment by motss** [comment]
Big thanks!
